In [1]:
import embedders

INFO: Using numpy backend


In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import embedders.manifolds


pm = embedders.manifolds.ProductManifold(signature=[(0, 8)])

In [3]:
sample = pm.sample(pm.mu0)

In [4]:
pm.manifold.logmap(pm.mu0, sample)

tensor([[ 0.2419, -0.0205,  1.9957, -0.8986, -0.3383, -0.0302, -1.2964, -1.0592]],
       grad_fn=<CatBackward0>)

In [5]:
sample

tensor([[ 0.2419, -0.0205,  1.9957, -0.8986, -0.3383, -0.0302, -1.2964, -1.0592]],
       grad_fn=<CatBackward0>)

In [6]:
import embedders

pm = embedders.manifolds.ProductManifold(signature=[(-1, 2), (0, 2), (1, 2)])

In [7]:
_m = pm.P[0].manifold

In [8]:
pm.mu0

tensor([1., 0., 0., 0., 0., 1., 0., 0.])

In [9]:
pm.ambient_dim

8

In [12]:
import torch
sam = torch.stack([pm.sample() for _ in range(10)])

pm.logmap(sam, base=pm.mu0)

tensor([[[ 0.0000e+00,  3.7757e-01, -6.0623e-01,  9.9979e-01,  4.7421e-01,
           0.0000e+00, -1.0952e+00, -3.4913e-01]],

        [[ 0.0000e+00,  1.6256e+00, -1.2329e+00,  6.2518e-02,  2.1618e-01,
           0.0000e+00,  4.4631e-01,  7.9177e-01]],

        [[ 0.0000e+00,  1.0730e+00, -3.4047e-01,  5.3398e-01,  5.3757e-01,
           0.0000e+00, -1.0448e+00,  5.9377e-01]],

        [[ 0.0000e+00, -1.2358e+00, -1.8372e+00,  1.1468e+00,  1.2585e+00,
           0.0000e+00,  6.3174e-01, -1.7462e+00]],

        [[ 0.0000e+00,  3.5947e-01,  1.6151e-03, -3.3443e-01, -1.0160e-01,
           0.0000e+00,  2.3179e-01,  5.0318e-02]],

        [[ 0.0000e+00, -6.8709e-01,  4.5553e-01, -7.6210e-03, -3.5125e-01,
           0.0000e+00, -3.9655e-01,  4.2721e-01]],

        [[ 0.0000e+00,  5.1779e-01, -1.4346e-01, -8.9483e-01, -1.1972e+00,
           0.0000e+00, -1.0568e+00, -3.4706e-01]],

        [[ 0.0000e+00, -2.0099e+00, -8.9830e-01, -8.5351e-01, -2.0102e-01,
           0.0000e+00, -3.9671e-01, 

In [ ]:
import torch

_sample = pm.sample()

TypeError: ProductManifold.sample() missing 1 required positional argument: 'z_mean'

In [13]:
_m.expmap

Scaled(Lorentz) manifold

In [ ]:
import numpy as np 